# Generated by Django 5.2.7 on 2025-11-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_moderator",
            field=models.BooleanField(default=False),
        ),
    ]
