# Generated by Django 5.2.7 on 2025-11-21 23:04

import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_of_request", models.TimeField(auto_now=True)),
                ("reason", models.CharField(max_length=100, null=True)),
                (
                    "round_trip",
                    models.BooleanField(
                        default=False,
                        help_text="Will the student come back to the flex room they left?",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, help_text="Has the request been approved?"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "join_code",
                    models.CharField(
                        default=rooms.models.generate_unique_join_code,
                        editable=False,
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "isFlexOne",
                    models.BooleanField(help_text="Is this a flex room during flex 1."),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of room for flex time.",
                        max_length=200,
                    ),
                ),
                ("max_students", models.IntegerField(default=20)),
                (
                    "open_room",
                    models.BooleanField(
                        default=False,
                        help_text="Is the room availible to all students?",
                    ),
                ),
            ],
        ),
    ]
