# Generated by Django 5.2.7 on 2025-11-21 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("moderators", "0002_initial"),
        ("rooms", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="requesting_student",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="active_requests",
            field=models.ManyToManyField(blank=True, to="rooms.request"),
        ),
        migrations.AddField(
            model_name="room",
            name="allowed_students",
            field=models.ManyToManyField(
                blank=True, related_name="room_allowed", to="students.student"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="current_students",
            field=models.ManyToManyField(blank=True, to="students.student"),
        ),
        migrations.AddField(
            model_name="room",
            name="moderator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_moderator",
                to="moderators.moderator",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="destination",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rooms.room",
            ),
        ),
    ]
