# Generated by Django 5.2.7 on 2025-12-30 18:40

import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='join_code',
            field=models.CharField(default=rooms.models.generate_unique_join_code, max_length=6, unique=True),
        ),
    ]
