# Generated by Django 6.0 on 2025-12-31 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0003_moderator_reviewed_requests'),
        ('rooms', '0004_remove_request_time_of_request_request_created_at_and_more'),
        ('students', '0002_remove_student_flex_active_student_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgin', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='request',
            name='returned',
            field=models.BooleanField(default=False, help_text='Has the student returned?'),
        ),
        migrations.AddField(
            model_name='request',
            name='reviewed_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderators.moderator'),
        ),
        migrations.AddField(
            model_name='room',
            name='flex_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requesting_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
        migrations.AlterField(
            model_name='request',
            name='round_trip',
            field=models.BooleanField(help_text='Will the student come back to the flex room they left?'),
        ),
    ]
