# Generated by Django 5.2.7 on 2025-10-24 01:27

import classroom.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requesting_student", models.UUIDField(default=None, null=True)),
                ("destination", models.UUIDField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "join_code",
                    models.CharField(
                        default=classroom.models.generate_unique_join_code,
                        editable=False,
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of room for flex time.",
                        max_length=200,
                    ),
                ),
                ("max_students", models.IntegerField(default=20)),
                ("student_count", models.IntegerField(default=0)),
                (
                    "open_room",
                    models.BooleanField(
                        default=False,
                        help_text="Is the room availible to all students?",
                    ),
                ),
                (
                    "allowed_students",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(default=None, null=True),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "isFlexOne",
                    models.BooleanField(help_text="Is this a flex room during flex 1."),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
