# Generated by Django 5.2.7 on 2025-10-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="time_of_request",
            field=models.TimeField(auto_now=True),
        ),
    ]
