# Generated by Django 5.2.7 on 2025-10-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0002_request_time_of_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="reason",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
