# Generated by Django 5.2.7 on 2025-10-24 02:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0003_request_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="student_count",
        ),
        migrations.AddField(
            model_name="classroom",
            name="active_requests",
            field=models.ManyToManyField(to="classroom.request"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="current_students",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(default=None, null=True),
                blank=True,
                default=None,
                size=None,
            ),
            preserve_default=False,
        ),
    ]
