# Generated by Django 5.2.7 on 2025-10-24 02:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0004_remove_classroom_student_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="allowed_students",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(default=None, null=True),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="current_students",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(default=None, null=True),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
