# Generated by Django 5.2.7 on 2025-10-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0005_alter_classroom_allowed_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="active_requests",
            field=models.ManyToManyField(blank=True, to="classroom.request"),
        ),
    ]
