# Generated by Django 5.2.7 on 2025-10-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0006_alter_classroom_active_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="approved",
            field=models.BooleanField(
                default=False, help_text="Has the request been approved?"
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="round_trip",
            field=models.BooleanField(
                default=False,
                help_text="Will the student come back to the flex room they left?",
            ),
        ),
    ]
