# Generated by Django 5.2.7 on 2025-11-21 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("moderators", "0001_initial"),
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="moderator",
            name="moderated_rooms",
            field=models.ManyToManyField(
                blank=True, related_name="moderator_rooms", to="rooms.room"
            ),
        ),
        migrations.AddField(
            model_name="moderator",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderator_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
