# Generated by Django 6.0 on 2025-12-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0002_initial'),
        ('rooms', '0004_remove_request_time_of_request_request_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='reviewed_requests',
            field=models.ManyToManyField(blank=True, to='rooms.request'),
        ),
    ]
