# Generated by Django 6.0 on 2025-12-31 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0003_moderator_reviewed_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='reviewed_requests',
        ),
    ]
