# Generated by Django 6.0 on 2025-12-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0004_remove_moderator_reviewed_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
